name: test_toilet_search
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  geolocator: ^9.0.2
  google_place: ^0.4.7
  http: ^0.13.5
  url_launcher: ^6.1.10

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
